## Image Processing - IP using OpenCV

In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
#conda install -c conda-forge opencv
#pip install opencv-python

In [15]:
import cv2

In [7]:
img = cv2.imread('/Users/sjsb/Downloads/Lenna.jpeg',1)
img.shape

(512, 512, 3)

In [9]:
img[:5, :5, 1]

array([[137, 137, 137, 136, 138],
       [137, 137, 137, 136, 138],
       [137, 137, 137, 136, 138],
       [137, 137, 137, 136, 138],
       [137, 137, 137, 136, 138]], dtype=uint8)

In [24]:
# img1 = cv2.imread('/Users/sjsb/Downloads/Lenna.jpeg',0)
# img1 = cv2.imread('/Users/sjsb/Downloads/lenna_gray.jpg',0)
img1 = cv2.imread('/Users/sjsb/Downloads/lenna_gray.png',0)
img1.shape

(512, 512)

In [25]:
img2 = cv2.imread('/Users/sjsb/Downloads/lenna_color.png',1)
img2.shape

(512, 512, 3)

In [30]:
img2[:5, :5, 0]
img2[:5, :5, 1]
img2[:5, :5, 2]

array([[121, 121, 129, 121, 121],
       [121, 121, 129, 121, 121],
       [121, 121, 129, 121, 121],
       [121, 121, 129, 121, 121],
       [121, 121, 129, 121, 121]], dtype=uint8)

array([[133, 133, 137, 133, 133],
       [133, 133, 137, 133, 133],
       [133, 133, 137, 133, 133],
       [133, 133, 137, 133, 133],
       [133, 133, 137, 133, 133]], dtype=uint8)

array([[222, 222, 226, 222, 222],
       [222, 222, 226, 222, 222],
       [222, 222, 226, 222, 222],
       [222, 222, 226, 222, 222],
       [222, 222, 226, 222, 222]], dtype=uint8)

In [ ]:
win_img = img2

In [ ]:
cv2.imshow('win_img', img2)